[package]
name = "ethereum-transfer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.14"
tokio = { version = "1.38.0", features = ["full"] }
dotenv = "0.15.0"