[package]
name = "ether-address"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
secp256k1 = "0.29.0"
sha3 = "0.10"
rayon = "1.7"
hex = "0.4"
num_cpus = "1.13"
rand = "0.8"
